# Generated by Django 3.1.7 on 2021-02-25 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='mutaxasislik')),
            ],
        ),
        migrations.CreateModel(
            name='Work_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ishlash kunlari')),
            ],
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Operatsiya')),
                ('specialties_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.specialties')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Doctor ism familiya')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=5, verbose_name='Jinsi')),
                ('age', models.IntegerField(verbose_name='Yoshi')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Raqami')),
                ('date_add', models.DateField(verbose_name='qowilgan vaqt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.province')),
                ('specialties_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.specialties')),
                ('work_time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.work_time')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tuman')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.province')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kassalik')),
                ('specialties_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.specialties')),
            ],
        ),
    ]
