# Generated by Django 3.1.7 on 2021-02-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_rating_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(max_length=50, verbose_name='asssd')),
            ],
        ),
    ]
