# Generated by Django 3.1.7 on 2021-02-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_camment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camment',
        ),
    ]
