# Generated by Django 3.1.7 on 2021-02-27 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_delete_camment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='body',
            field=models.TextField(default=1, verbose_name='Ummumiy malumot'),
            preserve_default=False,
        ),
    ]
