# Generated by Django 3.1.7 on 2021-03-04 05:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_doctor_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='specialties_id',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='specialties_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='condition_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='procedures_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.procedures'),
            preserve_default=False,
        ),
    ]
