# Generated by Django 3.1.7 on 2021-03-04 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20210304_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedures',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.doctor'),
            preserve_default=False,
        ),
    ]
