# Generated by Django 3.1.7 on 2021-03-05 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20210304_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.specialties'),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.specialties'),
        ),
    ]
