# Generated by Django 3.1.7 on 2021-03-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20210305_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='doctor_id',
            new_name='specialties_id',
        ),
        migrations.RenameField(
            model_name='procedures',
            old_name='doctor_id',
            new_name='specialties_id',
        ),
    ]
