# Generated by Django 3.1.7 on 2021-03-08 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20210307_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='work_experience',
            field=models.CharField(choices=[('<<5', '<<5'), ('5-10', '5-10'), ('10-20', '10-20'), ('20-30', '20-30'), ('30<<', '30<<')], default=1, max_length=5, verbose_name='work experience'),
            preserve_default=False,
        ),
    ]
