# Generated by Django 3.1.7 on 2021-03-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_doctor_work_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
